### ISSUE TITLE
Safari mobile needs playsInline attribute

### ISSUE THREAD

**Issue by ibrent** [Js-Brecht/gatsby-video-bg#1]
Adding the 'playsInline' attribute will allow Safari Mobile to play the videos correctly.  You may want to add that.  Also, like the 'autoPlay' attribute is camel-case, the 'playsInline' needs to be camel-case as well in Gatsby.

**Comment by Js-Brecht** [comment]
This repository was a very simple example in response to a question in Spectrum.  Tbh, I'm a bit surprised I never archived it :laughing:

I'll accept a PR, but I don't plan on taking the time to maintain this

**Comment by ibrent** [comment]
Cool

**Comment by Js-Brecht** [comment]
Thanks @ibrent.  Closed in #2
